name = "Gemoded Ist Geil"
author = "Laputa Werkstatt"
version = "1.0.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a2442a581f83d051d468947fb6bcfd8a1119785d0db793c12fe635adc47e3b3"
