name = "Gemoded Ist Geil"
author = "Laputa Werkstatt"
version = "1.0.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d00de41071bac521e3c0105eb7cd4106f9820cd396efbabbc1293c66063a4726"
